# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Concord < Formula
  desc "A Go CLI that triages security scanner findings with multiple LLMs."
  homepage "https://github.com/seschis/concord"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seschis/concord/releases/download/v0.0.2/concord_0.0.2_darwin_amd64.tar.gz"
      sha256 "b842f3796d3e293b710a32da193eb77dc415191c3b82d8751397514e659fd782"

      define_method(:install) do
        bin.install "concord"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seschis/concord/releases/download/v0.0.2/concord_0.0.2_darwin_arm64.tar.gz"
      sha256 "561a5315c2bca6fe9ceaffee691a919be6f629739964e46d9ac9827450955fa1"

      define_method(:install) do
        bin.install "concord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seschis/concord/releases/download/v0.0.2/concord_0.0.2_linux_amd64.tar.gz"
      sha256 "aae46afb1efef05f7267066e410983fc0bc14418fc687da506ade0414c7ba916"
      define_method(:install) do
        bin.install "concord"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seschis/concord/releases/download/v0.0.2/concord_0.0.2_linux_arm64.tar.gz"
      sha256 "b3f147a65101791cdeebde88551b5fbf48b1e554e56c74627a32c3362a0244ac"
      define_method(:install) do
        bin.install "concord"
      end
    end
  end
end
