# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harmonia < Formula
  desc "A Go CLI that triages security scanner findings with multiple LLMs."
  homepage "https://github.com/seschis/harmonia"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seschis/harmonia/releases/download/v0.1.0/harmonia_0.1.0_darwin_amd64.tar.gz"
      sha256 "6c017356c973437a1a1f0352468de6574567c982e4b8c241fbd8ad06e981fa58"

      define_method(:install) do
        bin.install "harmonia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seschis/harmonia/releases/download/v0.1.0/harmonia_0.1.0_darwin_arm64.tar.gz"
      sha256 "094cf3f57d8f38c0f7683fb84c18aa07f529c16fc05cdfd4ae93b1624cce6d98"

      define_method(:install) do
        bin.install "harmonia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seschis/harmonia/releases/download/v0.1.0/harmonia_0.1.0_linux_amd64.tar.gz"
      sha256 "5d9e6d5b7cf971acd8393aebed719818c0da26ec0e187f0c2b72ab9340d62dc8"
      define_method(:install) do
        bin.install "harmonia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seschis/harmonia/releases/download/v0.1.0/harmonia_0.1.0_linux_arm64.tar.gz"
      sha256 "fbc4d74b4c469cf139687becba168daa4420506310ab1fbd54770df6318e1b73"
      define_method(:install) do
        bin.install "harmonia"
      end
    end
  end
end
